# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://opentk.github.io" # the base hostname & protocol for your site

# custom settings

# this includes the pages subfolder, allowing a cleaner structure.
include: ["_pages"]

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: OpenTK
  logo: opentk-logo-white.png
  gravatar: # Email MD5 hash
  description: "A low-level, cross-platform C# for OpenGL, OpenCL and OpenAL" # used by search engines

  # Icons
  rss: false
  github: "opentk/opentk"
  gitter: "opentk/opentk"

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "View on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 2
paginate_path: "/blog/page:num/"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
